apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ivtis
  namespace: ace
spec:
  pod:
    containers:
      env:
      - name: MQSI_OVERRIDE_HOSTNAME
        value: "ace-ivtis.upstream-1-25-6-643d6b687ab93581d24420becac24aae-0000.au-syd.containers.appdomain.cloud"
      - name: MQSI_OVERRIDE_HTTPS_PORT
        value: "443"
      runtime:
        resources:
          limits:
            cpu: '0.5'
            memory: 2Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
  version: 12.0.7.0-r1
#  imagePullSecrets:
#    name: ibm-entitlement-key
  license:
    accept: true
    license: L-APEH-CJUCNR
    use: AppConnectEnterpriseProduction
  useCommonServices: false
  enableMetrics: false
  barURL: https://db-prod-dash:3443/v1/directories/Backend?c77e14fb-d93d-48c0-a950-16f3cfe8920b
  replicas: 1
  service:
    endpointType: https
  designerFlowsOperationMode: disabled
  adminServerSecure: false
  logFormat: basic
  configurations: [ "key.jks", "httpsconf"]
