apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: is2
  namespace: ace
spec:
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ace/demoace:v0.96
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.5'
            memory: 2Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
  version: 12.0.4.0-r2
  imagePullSecrets:
    name: default-dockercfg-kjxtv
  license:
    accept: true
    license: L-APEH-C9NCDM
    use: AppConnectEnterpriseNonProduction
  useCommonServices: true
  enableMetrics: true
  replicas: 1
  service:
    endpointType: https
  designerFlowsOperationMode: disabled
  adminServerSecure: false
  tracing:
    enabled: true
    namespace: od
  logFormat: basic
  configurations: ["mqpolicy", "key.jks", "kafkapolicy", "httpsconf", "scramparms", "es-cert-ace.jks"]
